# Generated by Django 5.1.6 on 2026-01-17 18:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Job description/requirements')),
                ('application_status', models.CharField(choices=[('yet_to_apply', 'Yet to Apply'), ('applied', 'Applied')], default='yet_to_apply', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_applied', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='MasterResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Master Resume', max_length=255)),
                ('latex_content', models.TextField(help_text='Complete LaTeX resume content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TailoredResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_suggested_latex', models.TextField(help_text='AI-generated LaTeX content')),
                ('current_latex', models.TextField(help_text='Current user-edited LaTeX content')),
                ('coolness_level', models.IntegerField(default=100, help_text='0-100, how close to AI suggestions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailored_resumes', to='api.jobapplication')),
                ('master_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailored_versions', to='api.masterresume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('contact', 'Contact Information'), ('summary', 'Summary'), ('experience', 'Experience'), ('education', 'Education'), ('skills', 'Skills'), ('other', 'Other')], max_length=20)),
                ('original_content', models.TextField(help_text='Original content from master resume')),
                ('ai_suggested_content', models.TextField(help_text='AI-suggested modifications')),
                ('final_content', models.TextField(help_text='Final user-edited content')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('tailored_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.tailoredresume')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
