# Generated by Django 5.1.6 on 2026-01-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('max_salary', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('cooked_level', models.IntegerField(default=0)),
                ('tasks', models.JSONField(default=dict)),
            ],
        ),
    ]
