# Generated by Django 5.1.6 on 2026-01-17 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoredresume',
            name='ai_suggestions',
            field=models.JSONField(default=list, help_text='List of AI suggestions for improvement'),
        ),
        migrations.AddField(
            model_name='tailoredresume',
            name='current_cookedness_score',
            field=models.IntegerField(default=100, help_text='Current cookedness score after improvements (0=perfect, 100=generic)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tailoredresume',
            name='improvement_history',
            field=models.JSONField(default=list, help_text='History of score changes and improvements made'),
        ),
        migrations.AddField(
            model_name='tailoredresume',
            name='initial_cookedness_score',
            field=models.IntegerField(default=100, help_text='Initial AI analysis score (0=perfect, 100=generic)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tailoredresume',
            name='ai_suggested_latex',
            field=models.TextField(blank=True, default='', help_text='AI-generated LaTeX content'),
        ),
        migrations.AlterField(
            model_name='tailoredresume',
            name='coolness_level',
            field=models.IntegerField(default=100, help_text='Legacy: Cooked level (0=uncooked/authentic, 100=overcooked/AI copy)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
