# Generated by Django 5.1.6 on 2026-01-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tailoredresume_ai_suggestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterresume',
            name='html_content',
            field=models.TextField(blank=True, default='', help_text='HTML resume content from rich text editor'),
        ),
        migrations.AddField(
            model_name='tailoredresume',
            name='current_html',
            field=models.TextField(default='', help_text='Current HTML resume content'),
        ),
        migrations.AlterField(
            model_name='masterresume',
            name='latex_content',
            field=models.TextField(blank=True, default='', help_text='Complete LaTeX resume content'),
        ),
        migrations.AlterField(
            model_name='tailoredresume',
            name='current_latex',
            field=models.TextField(blank=True, default='', help_text='Current user-edited LaTeX content'),
        ),
    ]
