# Generated by Django 5.1.6 on 2026-01-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_masterresume_html_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterresume',
            name='latex_content',
        ),
        migrations.RemoveField(
            model_name='tailoredresume',
            name='ai_suggested_latex',
        ),
        migrations.RemoveField(
            model_name='tailoredresume',
            name='current_latex',
        ),
    ]
