# Generated by Django 5.1.6 on 2026-01-18 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_latex_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoredresume',
            name='base_resume',
            field=models.ForeignKey(blank=True, help_text='Resume used as base (if built upon another tailored resume)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_resumes', to='api.tailoredresume'),
        ),
    ]
