# Generated by Django 5.1.6 on 2026-01-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_base_resume_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('Applying', 'Applying'), ('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Negotiating', 'Negotiating'), ('Accepted', 'Accepted'), ('No Response', 'No Response')], default='Applying', max_length=20),
        ),
    ]
