# Generated by Django 5.1.6 on 2026-01-18 18:51

from django.db import migrations


def migrate_statuses(apps, schema_editor):
    JobApplication = apps.get_model('api', 'JobApplication')
    # Update old statuses to new ones
    JobApplication.objects.filter(application_status='yet_to_apply').update(application_status='Applying')
    JobApplication.objects.filter(application_status='applied').update(application_status='Applied')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_update_job_status_choices'),
    ]

    operations = [
        migrations.RunPython(migrate_statuses, reverse_code=migrations.RunPython.noop),
    ]
