# Generated by Django 5.1.6 on 2026-01-18 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_migrate_old_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cooked_level',
            field=models.IntegerField(default=0, help_text='Resume cookedness level (0=perfect, 100=generic)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='deadline',
            field=models.DateField(blank=True, help_text='Application deadline', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='follow_up',
            field=models.DateField(blank=True, help_text='Follow up date', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Job location', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='max_salary',
            field=models.IntegerField(blank=True, help_text='Maximum salary', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='tasks',
            field=models.JSONField(blank=True, default=dict, help_text='Tasks/notes related to this job'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Job posting URL', max_length=1000),
        ),
    ]
